modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${git_issues}"
license = "MIT"

[[mods]]
modId = "foxbackport"
version = "${version}"
displayName = "FOX's Misc Figura Backport"
authors = "Bitslayn, PenguinEncounter"
displayTest = "IGNORE_ALL_VERSION"
description = "Backports popular changes and fixes from Figura 0.1.6s"
logoFile = "assets/foxbackport/icon.png"

[[dependencies.foxbackport]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.foxbackport]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_range_forge}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.foxbackport]]
modId = "figura"
mandatory = true
versionRange = "0.1.5,0.1.5b"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "foxbackport.mixins.json"